version: 0.2

phases:
  install:
    runtime-versions:
      java: 11
    commands:
      - echo "Installing dependencies"
      - apt install dos2unix -y
      - chmod +x install.sh
      - dos2unix ./install.sh
      - mvn install

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "$NUMBER.dkr.ecr.us-east-1.amazonaws.com"

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$NUMBER.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest" .

 
  post_build:
    commands:
      - echo "Checking IAM identity"
      - aws sts get-caller-identity
      - echo "Assuming EKS role"
      - export AWS_ROLE_ARN="arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_CODEBUILD_ROLE"
      - export AWS_WEB_IDENTITY_TOKEN_FILE=$(curl -sS 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq -r '.TokenFilePath')
      - aws eks update-kubeconfig --region us-east-1 --name mycluster --role-arn $AWS_ROLE_ARN
      - echo "Verifying Kubernetes access"
      - kubectl cluster-info
      - kubectl get nodes
      - echo "Deploying to EKS"
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl get svc
