version: 0.2

phases:
  install:
    runtime-versions:
      java: 11
    commands:
      - echo "Installing dependencies"
      - apt install dos2unix -y

  pre_build:
    commands:
      - echo "Building project with Maven"
      - mvn clean install -DskipTests
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 557690612191.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Checking if .war file exists..."
      - ls -lah target/
      - if [ ! -f target/vprofile-v2.war ]; then echo "ERROR: vprofile-v2.war NOT FOUND!"; exit 1; fi
      - echo "Building Docker image"
      - docker build -t 557690612191.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 557690612191.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      - echo "Checking IAM identity"
      - aws sts get-caller-identity
      - echo "Updating kubeconfig for EKS..."
      - aws eks update-kubeconfig --region us-east-1 --name mycluster
      - kubectl cluster-info
      - echo "Deploying to Kubernetes"
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl get svc
